### ISSUE TITLE
Selecting 1000 members is very slow

### ISSUE THREAD

**Issue by jorg-vr** [ScoutsGidsenVL/groepsadmin-frontend#17]
I wanted to sent emails to a selection of 1000 members, but they are loaded in batches of 50. And selecting all at the top only selects all members that are loaded. (Instead of all members that are fit the selection criteria)
It works if I scroll down and wait for the loading of new batches multiple times but this is way to slow.

**Comment by jorg-vr** [comment]
In the end I switched back to the old layout, which seems to do the batch selection of all members in the background

**Comment by jressen** [comment]
Thank you Jorg for your feedback.
While testing we noticed the same thing so this is being solved in the next couple of days.

**Comment by jressen** [comment]
We've made an adjustment, so the issue above should be fixed.
Pay attention that selecting a big number of members can be slower than expecting.
