### ISSUE TITLE
Mail send and save buttons appear before the menu

### ISSUE THREAD

**Issue by BavoVanCraeyenest** [ScoutsGidsenVL/groepsadmin-frontend#18]
When in the email screen and you hover over the menu the send and save email buttons are displayed before the menu instead of behind like the rest of the screen
![2023-05-07 18_03_20-Groepsadministratie Scouts en Gidsen Vlaanderen](https://user-images.githubusercontent.com/58469486/236688939-db8e7e8f-80b1-446c-8953-2655795bcf9a.png)

**Comment by jressen** [comment]
It was a z-index issue. This has been altered and it should appear correct now
