### ISSUE TITLE
Help button in the side menu doesn't do anything

### ISSUE THREAD

**Issue by BavoVanCraeyenest** [ScoutsGidsenVL/groepsadmin-frontend#19]
The help button in the side menu doesn't do anything. It even makes the menu disapp
![2023-05-07 18_05_44-Groepsadministratie Scouts en Gidsen Vlaanderen](https://user-images.githubusercontent.com/58469486/236689013-fabe519a-2cd3-41be-9fda-9f9515e3705d.png)
ear.

**Comment by jressen** [comment]
Issue should be solved. The link wasn't correct
