### ISSUE TITLE
When applying a group filter in the members screen the previous group filter is still displayed in the filter section although the new filter has been applied correctly 

### ISSUE THREAD

**Issue by BavoVanCraeyenest** [ScoutsGidsenVL/groepsadmin-frontend#20]
When you apply a new group filter in the members screen the previous group filter that you selected is still displayed in the filter section. The filter still correctly to the shown list. ![2023-05-07 18_10_03-Groepsadministratie Scouts en Gidsen Vlaanderen](https://user-images.githubusercontent.com/58469486/236689345-b1451ba5-4cc1-49bc-8e02-3324a8fb5ee1.png)

**Comment by jressen** [comment]
All issues should be reported to groepsadmin@scoutsengidsenvlaanderen.be
