### ISSUE TITLE
The button to switch to the old layout is not accessable anymore. In addition, the navigation menu on the left side disappears when scrolling down

### ISSUE THREAD

**Issue by kobe-michiels** [ScoutsGidsenVL/groepsadmin-frontend#21]
![image](https://github.com/ScoutsGidsenVL/groepsadmin-frontend/assets/116753368/4d8871ac-bdcd-4e54-b404-8a55ec988bb0)

![image](https://github.com/ScoutsGidsenVL/groepsadmin-frontend/assets/116753368/4b9a9d84-766f-4669-85b6-7e1340c3bfc8)

**Comment by jressen** [comment]
All issues should be reported to groepsadmin@scoutsengidsenvlaanderen.be
